### ISSUE TITLE
RAM Address？

### ISSUE THREAD

**Issue by PamiVOV** [nopnop2002/HT1621B#4]
```
void HT1621_write(uint8_t address, uint8_t data)
{
    TAKE_CS();
    HT1621_writeBits(WRITE_MODE, 3);
    HT1621_writeBits(address<<3, 6); // 6 is because max address is 128
    HT1621_writeBits(data, 8);
    RELEASE_CS();
}
```

> HT1621_writeBits(address<<3, 6);

The address should be moved 2 digits forward, not 3 digits?

**Comment by nopnop2002** [comment]
No
Command is 3bit.
Write Memory Address is 6bit.

Check page 10.
https://www.seeedstudio.com/document/HT1621.pdf

**Comment by nopnop2002** [comment]
Hello.
HT1621 have segment 0 to segment 31.
These module use from segment 1.
Segment 0 unused.
